### PR TITLE
Adding Navigation Design Patterns

### PR DESCRIPTION
**Pull request by jwijay**
Issue: https://github.com/grommet/hpe-design/issues/19
- waiting on small style fix for blockquote tags (to add margins to both top and bottom)

### CODE REVIEW

**Comment by L0ZZI** [comment]
This will need to live under the "Learn" area of the new grommet.io
When  releasing the new design, we'll add this content in.

**Comment by bryanjacquot** [comment]
Let's remove the Dashboard and Actions patterns on the new website, and replace the Navigation page with the content from this PR.

**Comment by ericsoderberghp** [comment]
FYI, I've manually merged this into the new-site branch of grommet-docs.

**Comment by bryanjacquot** [comment]
This PR is live here: http://grommet.github.io/docs/navigation

**Pull request closed without merging**
