### PR TITLE
Add Google Analytics Tracking / Page Views

### PR DESCRIPTION
**Pull request by RyanCCollins**
#### What does this PR do?
Adds Google Analytics tracking and page views

#### Where should the reviewer start?
`src/index.js` is where the tracker is initialized, but also checkout the utils that I added.  I wasn't sure of the best place to put these, so I made a utils folder within the `src` directory.  If you can think of a better place, please let me know and I'd be happy to change it.

#### What testing has been done on this PR?
I tested it manually by running the docs site and verifying that Google Analytics was capturing page views.

#### How should this be manually tested?
Launch the site locally and open the real-time overview on Google Analytics to see yourself get logged in real time.

#### Any background context you want to provide?
I was asked by Christina and Tracy to help get Google Analytics up and running for Grommet docs.

#### What are the relevant issues?
#274 

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by RyanCCollins** [comment]
@ericsoderberghp and I have been discussing putting the analytics utilities into Grommet so it might be a good idea to hold off on merging this until we decide on one way or the other.

**Comment by karatechops** [comment]
I understand this may not be our final solution to analytics but it would seem like we're missing out on page view metrics daily without adding some form of SPA analytics. I see there are analytics in a HTML script tag but I would presume this is only tracking the initial page view and not SPA navigation.

**Comment by RyanCCollins** [comment]
Good point @karatechops! 

It might make sense to merge this and remove the old tracker so that we can start getting page views asap.

**Comment by alansouzati** [comment]
nicely done! Thanks for your contribution!

**Pull request merged**
