### PR TITLE
Box direction defaults to row

### PR DESCRIPTION
**Pull request by mrexclamation**
Box direction defaults to row

### CODE REVIEW

**Comment by mrexclamation** [comment]
I think it should also explain that direction is inherited.

**Comment by alansouzati** [comment]
Hey. did you accidentally close this?

**Comment by mrexclamation** [comment]
Yeah I was confused, the default direction is column but I didn't know that also it is inherited

Sorry

**Comment by alansouzati** [comment]
it is ok, thanks for the initiative to send the PR in the first place.

**Pull request closed without merging**
